name: Alternate Linux Build

on:
  push:
    branches: [ develop ]

defaults:
  run:
    shell: bash

jobs:
  alternate_build_configurations:
    name: Alternate Compiler Configuration
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Set FC for Ubuntu 24.04
        run: echo "FC=gfortran-13" >> $GITHUB_ENV

      - name: Create Build Directory
        run: cmake -E make_directory ./build/

      - name: Configure CMake
        working-directory: ./build/
        run: >
          cmake
          -DCMAKE_BUILD_TYPE=Release
          -DLINK_WITH_PYTHON=OFF
          -DUSE_PSYCHROMETRICS_CACHING=OFF
          -DUSE_GLYCOL_CACHING=OFF
          -DOPENGL_REQUIRED=OFF
          -DUSE_PSYCH_STATS=ON
          -DUSE_PSYCH_ERRORS=OFF
          -DENABLE_PCH=OFF
          ../

      - name: Build EnergyPlus
        working-directory: ./build/
        run: cmake --build . --target energyplus -j 4
